FROM node:20-alpine

WORKDIR /app/apps/retailbot-api

COPY package.json ./../../package.json
COPY apps/retailbot-api/package.json ./package.json
COPY packages/ai-core ./../../packages/ai-core
COPY packages/data-models ./../../packages/data-models

RUN npm install --frozen-lockfile

COPY apps/retailbot-api .
COPY tsconfig.json ./../../tsconfig.json
COPY turbo.json ./../../turbo.json

RUN npm run build

CMD ["npm", "start"] 